site_description: Vue.js - The Progressive JavaScript Framework
google_analytics: UA-46852172-3
root_domain: v2.cn.vuejs.org
vue_version: 2.7.16
# START SPONSORS
platinum:
  - name: VueMastery
    url: https://www.vuemastery.com/
    img: vuemastery.png
  - name: VueSchool
    url: >-
      https://vueschool.io/?utm_source=Vuejs.org&utm_medium=Banner&utm_campaign=Sponsored%20Banner&utm_content=V1
    img: vueschool.png
  - name: Vehikl
    url: https://vehikl.com/
    img: vehikl.png
  - name: Vue.js Amsterdam
    url: https://vuejs.amsterdam/
    img: vue_js_amsterdam.png
  - name: Storyblok
    url: https://www.storyblok.com
    img: storyblok.png
  - name: Chrome Frameworks Fund
    url: https://opencollective.com/2021-frameworks-fund
    img: chrome_frameworks_fund.png
  - name: HeroDevs
    url: https://www.herodevs.com/support/vue
    img: herodevs.png
  - name: JavaScript Certification
    url: https://certificates.dev/javascript/?ref=vuejs-sponsor&friend=VUEJS
    img: javascript_certification.png?v2
    description: Certification of competence for the JavaScript language
  - name: 'CodeRabbit '
    url: >-
      https://www.coderabbit.ai?utm_source=github&utm_medium=sponsors&utm_campaign=evan_you_2025
    img: coderabbit_.png
  - name: aaPanel
    url: https://www.aapanel.com?invite_code=vue
    img: aapanel.png
  - name: ImageKit.io
    url: >-
      https://imagekit.io/?utm_source=vuejs&utm_medium=referral&utm_campaign=oss-sponsorship&utm_content=homepage
    img: imagekit_io.svg
gold:
  - name: Tidelift
    url: https://tidelift.com/subscription/npm/vue
    img: tidelift.png
  - name: Laravel
    url: https://laravel.com/
    img: laravel.png
  - name: DevExpress
    url: https://js.devexpress.com/
    img: devexpress.png
  - name: LY Corporation
    url: https://www.lycorp.co.jp/en/
    img: ly_corporation.png?v2
  - name: Fenêtre Online Solutions
    url: https://www.fenetre.nl/
    img: fen_tre_online_solutions.svg
  - name: Crisp
    url: https://crisp.chat/en/
    img: crisp.png
  - name: Localazy
    url: >-
      https://localazy.com/blog/how-to-localize-vuejs-app-with-vue-i18n-and-localazy?utm_source=vuejs&utm_medium=banner&utm_campaign=sponsorships_vuejs&utm_content=logo
    img: localazy.svg
  - name: Fathom Analytics
    url: https://usefathom.com/
    img: fathom_analytics.svg
  - name: Sentry
    url: https://sentry.io/for/vue?utm_source=vuejs.org&utm_medium=paid-community
    img: sentry.png
  - name: Certible
    url: https://www.certible.com
    img: certible.svg
  - name: FORTUNE GAMES
    url: https://www.fortunegames.com
    img: fortune_games.png
  - name: Quickbooks Tool Hub
    url: https://qbtoolhub.com/
    img: quickbooks_tool_hub.png
  - name: it@M
    url: ' https://opensource.muenchen.de/software/vue.js.html'
    img: it_m.png
  - name: Blastup
    url: https://blastup.com/buy-instagram-likes
    img: blastup.png
  - name: VueJobs
    url: https://vuejobs.com/?utm_source=vuejs.com&utm_campaign=sponsor
    img: vuejobs.png
  - name: Huly
    url: https://huly.io
    img: huly.svg
  - name: Automatenspieler
    url: https://automatenspieler.net/
    img: automatenspieler.png?v2
  - name: Stormlikes
    url: https://stormlikes.com
    img: stormlikes.png
  - name: Superviral
    url: https://superviral.io/
    img: superviral.png
  - name: Goread.io
    url: https://goread.io/buy-instagram-followers
    img: goread_io.png
  - name: LambdaTest
    url: https://lambdatest.com/
    img: lambdatest.svg
  - name: Leofame
    url: https://leofame.com/buy-instagram-followers
    img: leofame.png
  - name: SocialBoosting.com
    url: https://www.socialboosting.com/buy-tiktok-followers
    img: socialboosting_com.png
  - name: Poprey - Buy Instagram Likes
    url: https://poprey.com/
    img: poprey___buy_instagram_likes.png
  - name: Buy Instagram Followers Twicsy
    url: https://twicsy.com/buy-instagram-followers
    img: buy_instagram_followers_twicsy.png
  - name: https://casinobonuslord.com/
    url: https://casinobonuslord.com/
    img: https___casinobonuslord_com_.png
  - name: casinorevisor.com
    url: https://casinorevisor.com/
    img: casinorevisor_com.png
  - name: Daman Game
    url: https://damanapp.download/
    img: daman_game.png
  - name: Buy YouTube Views on Buzzoid
    url: https://buzzoid.com/buy-youtube-views/
    img: buy_youtube_views_on_buzzoid.png
  - name: Tiranga Game
    url: https://tirangagames.game
    img: tiranga_game.png
silver:
  - name: Doximity
    url: https://technology.doximity.com/
    img: doximity.png
  - name: Optimizers
    url: https://www.optimizers.nl
    img: optimizers.png
  - name: Indy
    url: https://www.indy.fr/
    img: indy.png
  - name: Buy Instagram Followers from SocialWick
    url: https://www.socialwick.com/instagram/followers
    img: buy_instagram_followers_from_socialwick.png
  - name: Social Followers
    url: https://www.socialfollowers.uk/buy-tiktok-followers/
    img: social_followers.png
  - name: Route Planner and Route Optimizer - Route4Me
    url: https://route4me.com
    img: route_planner_and_route_optimizer___route4me.png
  - name: Betwinner Partner
    url: https://betwinnerpartner.com/
    img: betwinner_partner.png
  - name: Buy Instagram followers
    url: https://skweezer.net/buy-instagram-followers
    img: buy_instagram_followers.png
  - name: Fansoria - Buy Instagram Followers
    url: https://www.fansoria.com/instagram-marketing/buy-instagram-followers/
    img: fansoria___buy_instagram_followers.png
  - name: Buy YouTube Subscribers Media Mister
    url: https://www.mediamister.com/buy-youtube-subscribers
    img: buy_youtube_subscribers_media_mister.png
bronze:
  - name: Derek Pollard
    url: https://polyglotengineer.com/derek.pollard
    img: derek_pollard.png
  - name: BGASoft
    url: https://www.bgasoft.com
    img: bgasoft.png
  - name: RStudio
    url: https://rstudio.com
    img: rstudio.png
  - name: codefortynine
    url: https://codefortynine.com
    img: codefortynine.png
  - name: Routr
    url: http://www.routr.com
    img: routr.png
platinum_china:
  - name: CRMEB
    url: http://github.crmeb.net/u/vue
    img: crmeb.svg?v2
    description: 开源电商系统
# END SPONSORS
video_china:
  - url: http://cloud.youku.com/index.php?source=vuejs
    img: youku.png
