name: Build and Deploy to GitHub

on:
  push:
    branches:
      - main

jobs:
  # 打包部署
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 切换分支
        uses: actions/checkout@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: 安装依赖
        run: npm install

      - name: 打包
        run: npm run build

      - name: 部署
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
