name: Build and Deploy to GitHub

on:
  push:
    branches:
      - main

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 切换分支
        uses: actions/checkout@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: 安装依赖
        run: npm install

      - name: 构建
        run: npm run build

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deploy job
  deploy:
    needs: build # 依赖 build 完成
    runs-on: ubuntu-latest

    steps:
      - name: 部署
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
